### ISSUE TITLE
SDK does not handle changes to DNS or temporary serving of Traefik self-signed certificates

### ISSUE THREAD

**Issue by markawightman75** [waives/waives.net#56]
**Describe the bug**
We have observed that if the SDK is operating (i.e. `HttpClient` has made at least one request) and Traefik is restarted and briefly serves its self-signed certificates before getting real ones then the SDK will retry the `AuthenticationException`s thrown by the `HttpClient` but the `HttpClient` does not recover once the real certificates are served again. We believe we will also see that DNS changes are also not respected once the `HttpClient` has been used.

**To Reproduce**
The easiest way (but it's still tricky) I've found to reproduce this is locally using Docker Compose with traefik configured to serve certificates. The key things you need to change to do this are:

Add this to Traefik's section in docker-compose.yaml:
```
   environment:
      - GCE_PROJECT=waivesiodns
      - GCE_SERVICE_ACCOUNT_FILE=/etc/traefik/google-acme-dns-service-account-credentials.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /dev/null:/traefik.toml
      - type: bind
        source: C:/temp/traefik
        target: /etc/traefik
```

Note that I had issues binding from a folder on anything other than C:\
Copy the google credentials json into that folder.
Create a basic traefik.toml file in that folder based on the production service version, with `dnsChallenge` set and make sure to have `acmeLogging=true` for visibility into certificate generation etc.

Note that the DNS check seems somewhat unreliable and sometimes times out so the certificate isn't created. The `delayBeforeCheck` property may help a bit, I couldn't be sure.

**Expected behaviour**
The pipeline resumes successfully when valid certificates begin to be served, and respects DNS changes.

**System details(please complete the following information):**
 - OS: Windows 10
 - CLR and version: netcoreapp2.1
 - SDK version: commit 41f244e

**Additional context**
See this article about `HttpClient`: http://www.nimaara.com/2016/11/01/beware-of-the-net-httpclient/ We should trying `Dispose()`ing the client and also using the code referenced in this article to limit the length of time each connection is kept alive for.
